# Generated by Django 3.1.7 on 2021-02-24 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schemas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('json_fields', models.JSONField()),
                ('modified', models.DateField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
                'permissions': (('manage_schema', 'Manage schema'),),
            },
        ),
        migrations.CreateModel(
            name='GeneratedSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('csv', models.FileField(blank=True, null=True, upload_to=schemas.models.content_file_name)),
                ('status', models.BooleanField(default=False)),
                ('schemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schemas')),
            ],
            options={
                'index_together': {('created', 'schemas')},
            },
        ),
    ]
