# Generated by Django 3.1.7 on 2021-02-23 17:39

from django.db import migrations, models
import django.db.models.deletion
import schemas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('json_fields', models.JSONField(default={})),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('csv', models.FileField(blank=True, null=True, upload_to=schemas.models.content_file_name)),
                ('status', models.BooleanField(default=False)),
                ('schemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schemas')),
            ],
            options={
                'index_together': {('created', 'schemas')},
            },
        ),
    ]
