# Generated by Django 3.1.7 on 2021-02-24 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemas',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
