# Generated by Django 3.1.7 on 2021-02-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210224_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemas',
            options={'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
    ]
