# Generated by Django 3.1.6 on 2021-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210210_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnschemas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
