# Generated by Django 3.1.6 on 2021-02-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20210213_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnschemas',
            name='field',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='columnschemas',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schemas.schemas'),
        ),
    ]
