# Generated by Django 3.1.6 on 2021-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20210213_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnschemas',
            name='field',
            field=models.JSONField(default='{}'),
        ),
    ]
