# Generated by Django 3.1.6 on 2021-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_auto_20210213_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='fields',
            field=models.JSONField(default='dict'),
        ),
    ]
