# Generated by Django 3.1.6 on 2021-02-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_auto_20210214_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemas',
            old_name='fields',
            new_name='json_fields',
        ),
    ]
