# Generated by Django 3.1.6 on 2021-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_auto_20210215_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemas',
            name='json_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
