# Generated by Django 3.1.6 on 2021-02-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0011_auto_20210218_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSchema',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schemas.schemas')),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schemas',
            name='json_fields',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='ColumnSchemas',
        ),
    ]
