# Generated by Django 3.1.6 on 2021-02-21 11:16

from django.db import migrations, models
import schemas.models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0012_auto_20210221_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedschema',
            old_name='modified',
            new_name='created',
        ),
        migrations.AddField(
            model_name='generatedschema',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to=schemas.models.content_file_name),
        ),
        migrations.AddField(
            model_name='generatedschema',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
