# Generated by Django 3.1.7 on 2021-02-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0014_auto_20210221_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedschema',
            old_name='shemas',
            new_name='schemas',
        ),
        migrations.AlterIndexTogether(
            name='generatedschema',
            index_together={('created', 'schemas')},
        ),
    ]
